### ISSUE TITLE
[feature request] raco file-watchers ....

### ISSUE THREAD

**Issue by bennn** [zyrolasting/file-watchers#2]
It'd be nice to be able to start a file watch using a [raco command](https://docs.racket-lang.org/raco/command.html):

```
$ raco file-watchers <my-file>
```

instead of running `main.rkt` directly.

**Comment by zyrolasting** [comment]
Hi @bennn 

Agreed, and apologies for the delay.

Please pull down #3 and run `raco pkg install --link` to try it out?

**Comment by zyrolasting** [comment]
Merged #3
