### ISSUE TITLE
Comments re: intensive model

### ISSUE THREAD

**Issue by zyrolasting** [zyrolasting/file-watchers#8]
Re: @dstorrs #6

> Regarding the intensive model, I'm concerned about its real-world
> usability, for two reasons:
> 
> 1) According to the docs it does not monitor directories, only files.
> 2) If there are, e.g. 1000 files in the directory then that's 1000
> threads.  I haven't explored how Racket handles large numbers of threads,
> but I would be concerned about the scheduler handling large numbers of
> threads in a timely way.

**Comment by zyrolasting** [comment]
On item 1, I'll ensure directories get monitored.

Re: item 2, my understanding is that the threads are cheap. To be fair, I base that on a comment from a community leader on Slack that met no push-back. I'm happy to optimize the model where possible, but I'm unsure how you can get the same kind of coverage the intensive watch promises without requiring one synchronizable event per file per change. Racket's per-file monitoring centers around synchronizable events, so if you didn't use a thread for each monitoring target and allowed a pseudorandom selection of a change event over a set of files, you'd just have the apathetic watch. If you know of a way to guarantee per-file, -directory, or -link coverage at the moment of change on a single thread, I'd be happy to follow that approach.

**Comment by dstorrs** [comment]
Makes sense.  Thanks for explaining.
